### ISSUE TITLE
Code issue.

### ISSUE THREAD

**Issue by CactusDuper** [Ruthacury/DreamCalculator#1]
You're using things like ```randFloat() <= 0.0473f``` when that's just not how it works. You have to actually simulate loot tables and use Java Random if you want accurate results. This could get you "close" but this isn't how the chances are calculated.

**Comment by Ruthacury** [comment]
I've changed it to be a bit closer to the actual calculation. I made this in like an hour, I never knew it would blow up on Reddit. I don't think that using C++ rand() instead of Java Random could make much of a difference. I'll leave this issue open for a while, if you have any feedback.

**Comment by CactusDuper** [comment]
The code is based on pre done statistics and not the actual data. C++ Rand is extremely different from Java Random and will absolutely make a difference in the results. As long as people aren't using this code to generate results as "proof" then it's okay. The entire core concept of the code would have to be changed in order for this to be more realistic. You need to simulate loot tables also. It's not a dig on you because it works as a quick tool to demonstrate some results but it shouldn't be used as any actual proof or comparison. <3

**Comment by Ruthacury** [comment]
I'll see if I can change to a Linear Congruent Generator, that should be far closer to Java Random. I appreciate the feedback!

**Comment by Ruthacury** [comment]
Although I suppose I would probably have to convert the entire program to java entirely for it to actually be useful as proof.

**Comment by CactusDuper** [comment]
Yeah. You would need to write it in java and simulate the loot table. I'm not saying what you currently have is "bad", it's just not technically correct. I think that what you're doing is a great idea and I'm happy to help!

**Comment by CactusDuper** [comment]
After talking with people in the technical community(one of them was someone who helped create the paper) they told me that there's just too many factors that contribute to the rng. Rewriting it in java won't make it accurate unfortunately as there's too many factors for this.

**Comment by psfree** [comment]
I implemented the basic Java RNG and I am about to make a pull request. Yes, it would be impossible to model the RNG perfectly because minecraft is a dynamic system (lava blocks for instance), however, using the LCG rng from Java will still make the results more accurate.

**Comment by CactusDuper** [comment]
Using LCGs will make the results more accurate but still not close enough to be considered "proof" or "100% accurate simulations". It does get you closer though!

**Comment by CactusDuper** [comment]
Part of the conversation I had with [Matthew Bolan](https://www.youtube.com/channel/UCB4XuRBJZBOpnoJSWekMohw):

Me: "I saw a post on reddit about calculating drop % in c++. I noticed it wasn't doing proper calculations after talking to [Cortex](https://github.com/MCRcortex). Do you think making it in Java would be better?"

Matthew: "I don't think a simulation using java would be accurate either. the noise from the runs themselves is a significant contributor to the randomness"

Unless you can somehow perfectly simulate everything that goes on, it's just not possible to have a 100% proper calculation. There's too many factors going on and it'd take exponentially longer to run the simulations.

**Comment by Ruthacury** [comment]
I agree it won't be possible to have a 100% accurate simulation. I think we can get closer by simulating the noise by having 6000 to 9000 calls to JavaRandom in between each pearl trade, and I'll have to check how many between each blaze kill. And also using separate RNG's as well for trades and blaze kills. Wouldn't be great for performance, but with psfree's improvements, it'll probably still be faster than it was before.

**Comment by Ruthacury** [comment]
Also something I've just noticed. When I run the program, after only a few million iterations, the maximum ender pearls is at 170, far above dream's 42, and the blaze rod max is at 291, also above dream's 211. The averages are also off, both are about +6 higher than they should be, ender pearls is at 16.13 (should be 262*20/423 = 12.39), and blaze rods are at 158.84 (should be 305*0.5 = 152.5). When I switched out JavaRandom for mt19937, the averages were correct again.

**Comment by psfree** [comment]
It might be a platform specific issue, I'll look into it. I spoke to the paper team yesterday, and I have a few other improvements in mind as well.

**Comment by Ruthacury** [comment]
I got this effect by creating 2 separate JavaRandoms and using one for ender pearls and one for blaze rods. Changing the seed to time(0) didn't make a difference, and neither did adding a few thousand j.nextInt() calls after each ender pearl calculations. I removed these as they made no difference. I'll push the changes to a separate branch soon.

**Comment by Ruthacury** [comment]
Done, changes are on the incorrect-averages branch.

**Comment by CactusDuper** [comment]
I would also recommend looking at KaptainWutax's FeatureUtils repo. Sorry for the delayed response.

@psfree Can I ask who you talked to specifically? 

@Ruthacury Yeah I'm not quite sure exactly why the rates were higher with jrand. I've been looking at loot table sim lately and I 100% recommend looking at KaptainWutax's FeatureUtils repo. I'm on mobile so I'll link it in the next comment

**Comment by CactusDuper** [comment]
https://github.com/KaptainWutax/FeatureUtils/tree/master/src/main/java/kaptainwutax/featureutils/loot

**Comment by CactusDuper** [comment]
Talked to people from the paper again. It's okay if you do use something like 20/423 since it really won't change the outcome

**Comment by Ruthacury** [comment]
Okay, so was it fine as it was originally with just "rand()%423 < 20"? (or rather "jrand()%423" now)
